#SECURITY BASED CONFIGURATIONS
app:
  config:
    keycloak:
      url: http://host.docker.internal:9080
      realm: electrical-vehicle

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            token-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/token
            authorization-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/auth
            user-name-attribute: preferred_username
            user-info-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/userinfo
            jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs
            user-info-authentication-method: header
        registration:
          internet-banking-core-client:
            provider: keycloak
            client-id: chargingstationservices
            client-secret: WnC9y8kKtVGJkSK2TJMFvhOTLdMbAlht
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9080/login/oauth2/code/keycloak
            scope: openid
      resourceserver:
        jwt:
          #useInsecureTrustManager: true
          jwk-set-uri: ${app.config.keycloak.url}/realms/${app.config.keycloak.realm}/protocol/openid-connect/certs